import os

#Folder with the source code in
rootFolder = "C:/Users/dp/Documents/My Games/Terraria/ModLoader/Mod Sources/PostMoonLord"
#Folders with modded content
folders = ["Buffs","Items","Mounts","NPCs","Projectiles","Tiles","Walls",]
#Wiki Home Page
homepage = "www.djpiper28.github.io/PostMoonLordWiki/index.html"

staticTitle = "<h1>Terraria: The Desomation of Moon Lord Wiki</h1>\n<p>This was auto generated by a python script made by djpiper28</p>\n<a href="+homepage+"\"\">Wiki homepage</a>"

items = []
#Get items:
for folder in folders:
	files = os.listdir(rootFolder+"/"+folder)
	ff = folder
	print("\n".join(files))
	for file in files:
		if ".cs" in file:
			print(file+" was a thing and was found")
			items.append(file+"|"+ff)

out = []

for item in items:

	print(item)
	itemFolder = item.split("|")[1]
	itemFile = item.split("|")[0]

	f = open((rootFolder+"/"+itemFolder+"/"+itemFile),"r")
	
	itemDetails = []

	for line in f:

		if "DisplayName.SetDefault" in line:
			itemDetails.append("Item Name: "+line.split("\"")[1]+"\n")
		
		if "Tooltip.SetDefault" in line:
			itemDetails.append("Item Description: "+line.split("\"")[1]+"\n")
		
		if "item.damage" in line:
			itemDetails.append("Item Damage: "+line.split("=")[1]+"\n")
		
		if "mod.ProjectileType" in line:
			itemDetails.append("Item Projectile: "+line.split("\"")[1]+"\n")
		
		if "item.lifeRegen" in line:
			itemDetails.append("Item Life Regen: "+line.split("=")[1]+"\n")
		
		if "item.useTime" in line:
			itemDetails.append("Item Use Time: "+line.split("=")[1]+"\n")
	
		if "item.knockBack" in line:
			itemDetails.append("Item Knockback: "+line.split("=")[1]+"\n")
	
		if "item.autoReuse" in line:
			itemDetails.append("Item Auto Swing: "+line.split("=")[1]+"\n")
	
		if "item.value" in line:
			itemDetails.append("Item Value: "+line.split("=")[1]+"\n")
		
		if "item.rare" in line:
			itemDetails.append("Item Rarity: "+line.split("=")[1]+"\n")
		
		if "name.SetDefault" in line:
			itemDetails.append("Tile Name: "+line.split("\"")[1]+"\n")
		
		if "Main.tileSpelunker" in line:
			itemDetails.append("Tile is an Ore: "+line.split("=")[1]+"\n")

		out.append("<p>"+"".join(itemDetails)+"</p>\n")

print("\n\n\n\n")
print("\n".join(out))

print(items)

i = 0

for data in out:

	if(i>=39):
		break

	d = staticTitle + data

	print(i)

	fileName = items[i].split("|")[0]
	fileName = fileName.split(".")[0]

	f = open(fileName+".html","w+")
	f.close
	f = open(fileName+".html","w")
	f.write(d)
	f.close

	i = i + 1

indexData = []

for item in items:

	fileName = item.split("|")[0]
	fileName = fileName.split(".")[0]

	indexData.append("<a href=\"www.djpiper28.github.io/"+(fileName+".html")+"\">"+fileName+"</a>\n")

print("Creating Index")
f = open("index.html", "w+")
f.close
print("Writing Data")
f = open("index.html", "w")
data_To_Write = "<h1>AutoGenerated Wiki Homepage</h1>"+staticTitle+"".join(indexData)
f.write(data_To_Write)
f.close
f.close
print(data_To_Write)
print("FINISHED")